name: Cleanup Old Workflows and Releases

on:
  # 每天凌晨3点执行（UTC时间）
#  schedule:
#    - cron: '0 3 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
      actions: write     
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 清理旧的工作流运行
      - name: Delete Old Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 5          
          keep_minimum_runs: 0    
          
      - name: Delete Old Releases
        uses: easingthemes/delete-old-releases@v0.2.0
        with:
         keep_latest: 5           
         older_than: 5            
         env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
